// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Proves typed IPC end to end. */
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**  Crate version for the About surface. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	getConfig: () => typedError<AppConfig_Serialize, string>(__TAURI_INVOKE("get_config")),
	/**  Send a message to the coding agent; streams over `harness_event`. */
	harnessAgentSend: (message: string, reasoningEffort: string | null, attachments: SendAttachment_Deserialize[] | null) => typedError<RunResult_Serialize, string>(__TAURI_INVOKE("harness_agent_send", { message, reasoningEffort, attachments })),
	/**  Stop the running agent loop. */
	harnessAgentAbort: () => typedError<null, string>(__TAURI_INVOKE("harness_agent_abort")),
	/**  Queue a user message into the running loop (next turn boundary). */
	harnessAgentSteer: (message: string) => typedError<null, string>(__TAURI_INVOKE("harness_agent_steer", { message })),
	/**  Clear the live transcript (keeps saved sessions). */
	harnessAgentReset: () => typedError<null, string>(__TAURI_INVOKE("harness_agent_reset")),
	/**  Start a fresh roleplay chat seeded with the selected greeting. */
	roleplayStartChat: () => typedError<string | null, string>(__TAURI_INVOKE("roleplay_start_chat")),
	/**  Send a message in the roleplay profile; streams over `talk_event`. */
	talkSend: (message: string, reasoningEffort: string | null, attachments: SendAttachment_Deserialize[] | null) => typedError<RunResult_Serialize, string>(__TAURI_INVOKE("talk_send", { message, reasoningEffort, attachments })),
	/**  Stop the running talk loop. */
	talkAbort: () => typedError<null, string>(__TAURI_INVOKE("talk_abort")),
	/**  Current talk transcript; lazily loads the active character's thread. */
	talkHistory: () => typedError<HistoryView_Serialize, string>(__TAURI_INVOKE("talk_history")),
	/**  Drop the last exchange from the talk thread. */
	talkRewind: () => typedError<null, string>(__TAURI_INVOKE("talk_rewind")),
	/**  Force-summarize older turns in the talk thread. */
	talkCompact: () => typedError<number, string>(__TAURI_INVOKE("talk_compact")),
	/**  Distill the talk thread into the character's memory, then start fresh. */
	talkDistill: () => typedError<string, string>(__TAURI_INVOKE("talk_distill")),
	/**  Context usage for the roleplay/Talk transcript. */
	talkContextStats: () => typedError<ContextStats_Serialize, string>(__TAURI_INVOKE("talk_context_stats")),
	/**  Answer an ask_user question parked by the talk run. */
	talkQuestionAnswer: (answer: string) => typedError<null, string>(__TAURI_INVOKE("talk_question_answer", { answer })),
	/**  Clear the task list (user action from the checkpoint strip). */
	harnessTodosClear: () => typedError<null, string>(__TAURI_INVOKE("harness_todos_clear")),
	/**  Distill the session into memory, coalesce the memories, then start fresh. */
	harnessDistill: () => typedError<string, string>(__TAURI_INVOKE("harness_distill")),
	/**  Current transcript for rebuilding the view (sessions, restarts). */
	harnessAgentHistory: () => typedError<HistoryView_Serialize, string>(__TAURI_INVOKE("harness_agent_history")),
	harnessAgentDecide: (grant: string | null) => typedError<null, string>(__TAURI_INVOKE("harness_agent_decide", { grant })),
	harnessQuestionAnswer: (answer: string) => typedError<null, string>(__TAURI_INVOKE("harness_question_answer", { answer })),
	/**
	 *  The built-in agent system prompt (before the project directory line is
	 *  appended). Shown in Settings so the user can see what the default is.
	 */
	getHarnessSystemPromptDefault: () => typedError<string, string>(__TAURI_INVOKE("get_harness_system_prompt_default")),
	harnessSessionsList: () => typedError<SessionSummary_Serialize[], string>(__TAURI_INVOKE("harness_sessions_list")),
	harnessSessionLoad: (id: string) => typedError<HistoryView_Serialize, string>(__TAURI_INVOKE("harness_session_load", { id })),
	harnessSessionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("harness_session_delete", { id })),
	/**  Restore the most recently deleted session (in-memory copy, short window). */
	harnessSessionUndo: () => typedError<string | null, string>(__TAURI_INVOKE("harness_session_undo")),
	harnessSessionRename: (id: string, title: string) => typedError<null, string>(__TAURI_INVOKE("harness_session_rename", { id, title })),
	/**  Write the session transcript JSON to a user-picked path. */
	harnessSessionExport: (id: string, path: string) => typedError<null, string>(__TAURI_INVOKE("harness_session_export", { id, path })),
	harnessProjectAdd: (path: string) => typedError<HarnessProject, string>(__TAURI_INVOKE("harness_project_add", { path })),
	harnessProjectRemove: (id: string) => typedError<null, string>(__TAURI_INVOKE("harness_project_remove", { id })),
	harnessProjectRename: (id: string, name: string) => typedError<null, string>(__TAURI_INVOKE("harness_project_rename", { id, name })),
	/**  Read-only allowlist for the active project (applies on next run). */
	setHarnessProjectExtraRead: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("set_harness_project_extra_read", { paths })),
	harnessGitIsRepo: (root: string) => typedError<boolean, string>(__TAURI_INVOKE("harness_git_is_repo", { root })),
	harnessWorktreeList: (root: string) => typedError<WorktreeDto_Serialize[], string>(__TAURI_INVOKE("harness_worktree_list", { root })),
	/**  Create a branch worktree in a sibling folder; returns its path. */
	harnessWorktreeAdd: (root: string, branch: string) => typedError<string, string>(__TAURI_INVOKE("harness_worktree_add", { root, branch })),
	harnessWorktreeRemove: (root: string, path: string, force: boolean) => typedError<null, string>(__TAURI_INVOKE("harness_worktree_remove", { root, path, force })),
	harnessProjectSetActive: (id: string | null) => typedError<null, string>(__TAURI_INVOKE("harness_project_set_active", { id })),
	setHarnessRoles: (orchestrator: string | null, worker: string | null) => typedError<null, string>(__TAURI_INVOKE("set_harness_roles", { orchestrator, worker })),
	/**  Per-role server overrides; None inherits the default. */
	setRoleParams: (role: string, ctxSize: number | null, nGpuLayers: number | null) => typedError<null, string>(__TAURI_INVOKE("set_role_params", { role, ctxSize, nGpuLayers })),
	/**  Attach/detach a companion file for one router role. */
	setRoleAttachment: (role: string, kind: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_role_attachment", { role, kind, enabled })),
	setMaxTurns: (orchestrator: number, subagent: number) => typedError<null, string>(__TAURI_INVOKE("set_max_turns", { orchestrator, subagent })),
	setVerifyMode: (mode: string) => typedError<null, string>(__TAURI_INVOKE("set_verify_mode", { mode })),
	/**  Override the system prompt (empty resets to built-in); next run. */
	setSystemPrompt: (prompt: string) => typedError<null, string>(__TAURI_INVOKE("set_system_prompt", { prompt })),
	/**  Replace the named system prompt presets (max 5, names trimmed). */
	setSystemPromptPresets: (presets: SystemPromptPreset[]) => typedError<null, string>(__TAURI_INVOKE("set_system_prompt_presets", { presets })),
	roleplayListCards: () => typedError<CardSummary[], string>(__TAURI_INVOKE("roleplay_list_cards")),
	roleplayImportCard: (path: string) => typedError<CardSummary, string>(__TAURI_INVOKE("roleplay_import_card", { path })),
	roleplayGetCard: (id: string) => typedError<CharacterCard, string>(__TAURI_INVOKE("roleplay_get_card", { id })),
	roleplayDeleteCard: (id: string) => typedError<null, string>(__TAURI_INVOKE("roleplay_delete_card", { id })),
	roleplayCardAvatar: (id: string) => typedError<string | null, string>(__TAURI_INVOKE("roleplay_card_avatar", { id })),
	setChatProfile: (profile: ChatProfile) => typedError<null, string>(__TAURI_INVOKE("set_chat_profile", { profile })),
	setRoleplayConfig: (roleplay: RoleplayConfig_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_roleplay_config", { roleplay })),
	/**  Import (or clear) the user's avatar for Talk bubbles. */
	roleplaySetUserAvatar: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("roleplay_set_user_avatar", { path })),
	/**  The user's avatar as a data URL, when one is set. */
	roleplayUserAvatar: () => typedError<string | null, string>(__TAURI_INVOKE("roleplay_user_avatar")),
	/**
	 *  Housekeeping model target (`provider:model`, `orchestrator`, `worker` or
	 *  none); next run.
	 */
	setUtilityTarget: (target: string | null) => typedError<null, string>(__TAURI_INVOKE("set_utility_target", { target })),
	/**  Toggle language-server diagnostics and the `lsp` tool for the next run. */
	setLspEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_lsp_enabled", { enabled })),
	/**  Hide or show `AGENTS.md`/`.agent*` files for every agent tool. */
	setAgentFilesHidden: (hidden: boolean) => typedError<null, string>(__TAURI_INVOKE("set_agent_files_hidden", { hidden })),
	/**  Save the sensitive-file policy lists (extra patterns + allow exceptions). */
	setSensitiveShielding: (patterns: string[], allow: string[]) => typedError<null, string>(__TAURI_INVOKE("set_sensitive_shielding", { patterns, allow })),
	/**  Enable/disable one agent tool for future runs. */
	setAgentToolEnabled: (name: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_agent_tool_enabled", { name, enabled })),
	/**  Replace the configured stdio language servers. */
	setLspServers: (servers: LspServerConfig_Deserialize[]) => typedError<null, string>(__TAURI_INVOKE("set_lsp_servers", { servers })),
	/**  Restore the built-in language-server list. */
	resetLspServers: () => typedError<LspServerConfig_Serialize[], string>(__TAURI_INVOKE("reset_lsp_servers")),
	/**  One command per sound to avoid clobbering via stale snapshots. */
	setSoundAgent: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_sound_agent", { enabled })),
	setSoundPermissions: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_sound_permissions", { enabled })),
	setSoundErrors: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_sound_errors", { enabled })),
	/**  Drop the last assistant response and the user turn that produced it. */
	harnessAgentRewind: () => typedError<null, string>(__TAURI_INVOKE("harness_agent_rewind")),
	/**  Force-summarize older turns now; returns the folded message count. */
	harnessAgentCompact: () => typedError<number, string>(__TAURI_INVOKE("harness_agent_compact")),
	/**
	 *  Read a user-picked file for sending: images as base64 (15 MB cap),
	 *  anything else as text (200 KB cap).
	 */
	harnessReadAttachment: (path: string) => typedError<AttachmentRead_Serialize, string>(__TAURI_INVOKE("harness_read_attachment", { path })),
	harnessAgentCapabilities: () => typedError<HarnessCapabilities_Serialize, string>(__TAURI_INVOKE("harness_agent_capabilities")),
	harnessReasoningOptions: () => typedError<ReasoningOptions, string>(__TAURI_INVOKE("harness_reasoning_options")),
	harnessContextStats: () => typedError<ContextStats_Serialize, string>(__TAURI_INVOKE("harness_context_stats")),
	toolsList: () => typedError<ToolsList, string>(__TAURI_INVOKE("tools_list")),
	pluginSetEnabled: (name: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("plugin_set_enabled", { name, enabled })),
	/**
	 *  Create a commented plugin template in the global plugins folder (the one
	 *  the Tools page lists); returns the manifest path so the UI can open it.
	 */
	scaffoldPlugin: () => typedError<string, string>(__TAURI_INVOKE("scaffold_plugin")),
	skillsList: () => typedError<SkillDto[], string>(__TAURI_INVOKE("skills_list")),
	harnessMemoryGet: (scope: string) => typedError<MemoryFileDto_Serialize, string>(__TAURI_INVOKE("harness_memory_get", { scope })),
	harnessMemorySet: (scope: string, text: string) => typedError<null, string>(__TAURI_INVOKE("harness_memory_set", { scope, text })),
	/**  Platform idiom for corner/shape theming (no inputs needed). */
	getPlatformStyle: () => typedError<PlatformStyle, string>(__TAURI_INVOKE("get_platform_style")),
	setWizardCompleted: (completed: boolean) => typedError<null, string>(__TAURI_INVOKE("set_wizard_completed", { completed })),
	getSystemInfo: () => typedError<SystemInfoDto_Serialize, string>(__TAURI_INVOKE("get_system_info")),
	/**  Usable assets in the latest release, best score first (wizard picker). */
	checkRelease: () => typedError<ReleaseDto, string>(__TAURI_INVOKE("check_release")),
	getServerStatus: () => typedError<ServerStatus, string>(__TAURI_INVOKE("get_server_status")),
	getServerLogs: () => typedError<string[], string>(__TAURI_INVOKE("get_server_logs")),
	getServerTools: () => typedError<ServerToolInfo[], string>(__TAURI_INVOKE("get_server_tools")),
	getServerInfo: () => typedError<ServerInfo_Serialize, string>(__TAURI_INVOKE("get_server_info")),
	setTools: (tools: string[]) => typedError<null, string>(__TAURI_INVOKE("set_tools", { tools })),
	listMcpServers: () => typedError<McpInfo, string>(__TAURI_INVOKE("list_mcp_servers")),
	saveMcpServers: (servers: McpServerEntry[]) => typedError<null, string>(__TAURI_INVOKE("save_mcp_servers", { servers })),
	/**
	 *  MCP server status. `probe = false` only reports cached state (nothing is
	 *  started); `probe = true` starts the servers once and refreshes the tool
	 *  cache — the explicit "Check now" path.
	 */
	getMcpAgentTools: (probe: boolean) => typedError<McpServerStatus_Serialize[], string>(__TAURI_INVOKE("get_mcp_agent_tools", { probe })),
	/**  Project folder tree with modification markers for the Chat sidebar. */
	projectFileTree: () => typedError<ProjectFiles_Serialize, string>(__TAURI_INVOKE("project_file_tree")),
	/**  Rename one file or folder inside the project (user action from the tree). */
	projectRenameEntry: (path: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("project_rename_entry", { path, newName })),
	/**  Move one file or folder to the OS trash (user action from the tree). */
	projectDeleteEntry: (path: string) => typedError<null, string>(__TAURI_INVOKE("project_delete_entry", { path })),
	stopServer: () => typedError<null, string>(__TAURI_INVOKE("stop_server")),
	/**  Persisted single/router mode; takes effect on the next server start. */
	setServerMode: (mode: ServerMode) => typedError<null, string>(__TAURI_INVOKE("set_server_mode", { mode })),
	/**  Replace the external OpenAI-compatible provider list. */
	setProviders: (providers: Provider_Deserialize[]) => typedError<null, string>(__TAURI_INVOKE("set_providers", { providers })),
	/**  External API mode target (`provider-id:model-id`); empty clears it. */
	setExternalTarget: (target: string | null) => typedError<null, string>(__TAURI_INVOKE("set_external_target", { target })),
	/**  Starred `provider-id:model-id` targets for the Mode picker. */
	setProviderFavorites: (favorites: string[]) => typedError<null, string>(__TAURI_INVOKE("set_provider_favorites", { favorites })),
	/**  Fetch the model ids a provider advertises (`GET /models`). */
	testProvider: (baseUrl: string, apiKey: string | null) => typedError<string[], string>(__TAURI_INVOKE("test_provider", { baseUrl, apiKey })),
	startServer: (config: ServerConfig) => typedError<null, string>(__TAURI_INVOKE("start_server", { config })),
	/**
	 *  Auto-start the local server before a chat run when enabled; waits until it
	 *  is ready. No-op when disabled, already running, or in External mode.
	 */
	ensureServer: () => typedError<null, string>(__TAURI_INVOKE("ensure_server")),
	/**  Save the local-server lifecycle settings. */
	setServerLifecycle: (autoStart: boolean, idleUnloadMinutes: number) => typedError<null, string>(__TAURI_INVOKE("set_server_lifecycle", { autoStart, idleUnloadMinutes })),
	/**  Current terminal working directory; `reset` re-derives it from the project. */
	terminalCwd: (reset: boolean) => typedError<string, string>(__TAURI_INVOKE("terminal_cwd", { reset })),
	/**
	 *  Run one command in the project folder; output streams over
	 *  `terminal_output` / `terminal_done`.
	 */
	terminalExec: (command: string) => typedError<null, string>(__TAURI_INVOKE("terminal_exec", { command })),
	/**  Stop the running command (and its children). */
	terminalKill: () => typedError<null, string>(__TAURI_INVOKE("terminal_kill")),
	previewServerArgs: (config: ServerConfig) => typedError<LaunchPreview, string>(__TAURI_INVOKE("preview_server_args", { config })),
	listInstalledModels: () => typedError<ModelDto_Serialize[], string>(__TAURI_INVOKE("list_installed_models")),
	deleteModel: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_model", { path })),
	setSelectedModel: (modelPath: string | null) => typedError<null, string>(__TAURI_INVOKE("set_selected_model", { modelPath })),
	toggleFavoriteModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("toggle_favorite_model", { modelId })),
	getModelDirs: () => typedError<ModelDirs, string>(__TAURI_INVOKE("get_model_dirs")),
	addModelDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("add_model_dir", { path })),
	removeModelDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("remove_model_dir", { path })),
	setDownloadDir: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_download_dir", { path })),
	getHfRepoFiles: (repoId: string) => typedError<HfFileDto_Serialize[], string>(__TAURI_INVOKE("get_hf_repo_files", { repoId })),
	searchHfModels: (query: string, owner: string | null, sort: string | null) => typedError<HfModel[], string>(__TAURI_INVOKE("search_hf_models", { query, owner, sort })),
	getKnownOwners: () => typedError<KnownOwnerDto[], string>(__TAURI_INVOKE("get_known_owners")),
	setPreferredOwners: (owners: string[]) => typedError<null, string>(__TAURI_INVOKE("set_preferred_owners", { owners })),
	validateHfOwner: (owner: string) => typedError<boolean, string>(__TAURI_INVOKE("validate_hf_owner", { owner })),
	/**
	 *  Download a repo file plus optional split parts under one progress id;
	 *  `save_as` renames the main file (companion sidecars). Returns the main file.
	 */
	downloadModel: (repoId: string, filename: string, splitParts: string[] | null, saveAs: string | null) => typedError<string, string>(__TAURI_INVOKE("download_model", { repoId, filename, splitParts, saveAs })),
	cancelDownload: (id: string) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { id })),
	/**  Stop a download but keep the partial for resume. */
	pauseDownload: (id: string) => typedError<null, string>(__TAURI_INVOKE("pause_download", { id })),
	/**  Stop a download and discard its partial file (split parts included). */
	discardDownload: (repoId: string, filename: string, splitParts: string[] | null, saveAs: string | null) => typedError<null, string>(__TAURI_INVOKE("discard_download", { repoId, filename, splitParts, saveAs })),
	getRuntimeInfo: () => typedError<RuntimeInfo_Serialize, string>(__TAURI_INVOKE("get_runtime_info")),
	downloadRuntimeLatest: () => typedError<null, string>(__TAURI_INVOKE("download_runtime_latest")),
	/**  Download one chosen asset from the latest release (wizard picker). */
	downloadRuntimeAsset: (assetName: string) => typedError<null, string>(__TAURI_INVOKE("download_runtime_asset", { assetName })),
	/**  Server binaries under a directory (existing-installation picker). */
	scanCustomBinaries: (path: string) => typedError<FoundBinaryDto[], string>(__TAURI_INVOKE("scan_custom_binaries", { path })),
	/**  Curated starter models with installed state. */
	recommendedModels: () => typedError<RecommendedDto_Serialize[], string>(__TAURI_INVOKE("recommended_models")),
	setActiveRuntime: (selection: ActiveRuntime) => typedError<null, string>(__TAURI_INVOKE("set_active_runtime", { selection })),
	deleteManagedRuntime: (build: number, backendId: string) => typedError<null, string>(__TAURI_INVOKE("delete_managed_runtime", { build, backendId })),
	/**  Drop older builds of the same backend when a new one finishes installing. */
	setAutoDeleteRuntimes: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_auto_delete_runtimes", { enabled })),
	addCustomRuntime: (path: string) => typedError<number, string>(__TAURI_INVOKE("add_custom_runtime", { path })),
	removeCustomRuntime: (index: number) => typedError<null, string>(__TAURI_INVOKE("remove_custom_runtime", { index })),
	listPresets: () => typedError<string[], string>(__TAURI_INVOKE("list_presets")),
	resetDefaultPreset: () => typedError<null, string>(__TAURI_INVOKE("reset_default_preset")),
	loadPreset: (name: string) => typedError<ServerConfig, string>(__TAURI_INVOKE("load_preset", { name })),
	savePreset: (name: string, config: ServerConfig) => typedError<null, string>(__TAURI_INVOKE("save_preset", { name, config })),
	deletePreset: (name: string) => typedError<null, string>(__TAURI_INVOKE("delete_preset", { name })),
	getModelPreset: (modelPath: string) => typedError<string | null, string>(__TAURI_INVOKE("get_model_preset", { modelPath })),
	setModelPreset: (modelPath: string, preset: string | null) => typedError<null, string>(__TAURI_INVOKE("set_model_preset", { modelPath, preset })),
	setLastPreset: (name: string | null) => typedError<null, string>(__TAURI_INVOKE("set_last_preset", { name })),
	setBenchVisible: (visible: boolean) => typedError<null, string>(__TAURI_INVOKE("set_bench_visible", { visible })),
	setCloseToTray: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray", { enabled })),
	setAutoCheckUpdates: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_auto_check_updates", { enabled })),
	runBench: (modelPath: string, nGpuLayers: number | null) => typedError<BenchResult_Serialize, string>(__TAURI_INVOKE("run_bench", { modelPath, nGpuLayers })),
	benchHistory: () => typedError<BenchResult_Serialize[], string>(__TAURI_INVOKE("bench_history")),
	clearBenchHistory: () => typedError<null, string>(__TAURI_INVOKE("clear_bench_history")),
	estimateMemory: (modelPath: string, nCtx: number, cacheTypeK: string, cacheTypeV: string, nGpuLayers: number, fit: boolean) => typedError<MemoryEstimate, string>(__TAURI_INVOKE("estimate_memory", { modelPath, nCtx, cacheTypeK, cacheTypeV, nGpuLayers, fit })),
	/**  Hardware-aware launch suggestion from the model header (auto-estimate). */
	suggestServerConfig: (modelPath: string, modelSizeMb: number) => typedError<ServerConfig, string>(__TAURI_INVOKE("suggest_server_config", { modelPath, modelSizeMb })),
	/**  Size-only suggestion (no header read); notes for the estimate card. */
	suggestModelConfig: (modelSizeMb: number) => typedError<SuggestedConfig, string>(__TAURI_INVOKE("suggest_model_config", { modelSizeMb })),
};

/* Types */
export type ActiveRuntime = { type: "managed"; build: number; backend_id?: string } | { type: "custom"; index: number } | { type: "none" };

export type AppConfig = AppConfig_Serialize | AppConfig_Deserialize;

export type AppConfig_Deserialize = {
	version?: number,
	/**  First-launch wizard done; `--force-wizard` clears it for this run. */
	wizard_completed?: boolean,
	managed_runtimes?: ManagedRuntime[],
	custom_runtimes?: CustomRuntime[],
	active_runtime?: ActiveRuntime,
	model_dirs?: string[],
	download_dir?: string | null,
	favorite_models?: string[],
	selected_model?: string | null,
	plugin_disabled?: string[],
	/**  Turn budget for the orchestrator loop. */
	harness_max_turns?: number,
	/**  Turn budget per subagent run. */
	harness_subagent_max_turns?: number,
	/**  Verification-nudge strictness for the agent loop. */
	verify_mode?: VerifyMode,
	/**  Custom system prompt override; None means the built-in default. */
	harness_system_prompt?: string | null,
	/**  Named system prompt presets (quick swap in Settings). */
	system_prompt_presets?: SystemPromptPreset[],
	/**  Agent (coding harness) or Roleplay (character cards). */
	chat_profile?: ChatProfile,
	/**  Roleplay: active card, persona, greeting, sampling overrides. */
	roleplay?: RoleplayConfig_Deserialize,
	/**
	 *  Housekeeping model for compaction and distillation: a `provider:model`
	 *  target or a local role (`orchestrator`/`worker`). None = main model.
	 */
	utility_target?: string | null,
	/**  Language-server diagnostics after edits and the `lsp` query tool. */
	lsp_enabled?: boolean,
	/**  Single-model or router server mode (Mode tab). */
	server_mode?: ServerMode,
	/**  Agent tool names the harness must not offer; empty enables all. */
	agent_tools_disabled?: string[],
	/**  Hide `AGENTS.md`/`.agent*` files from every agent tool when set. */
	agent_files_hidden?: boolean,
	/**  Extra sensitive-file globs for agent tools (on top of the built-ins). */
	sensitive_patterns?: string[],
	/**  Exceptions to the sensitive-file policy (globs). */
	sensitive_allow?: string[],
	/**  Start the local server automatically when a chat run begins. */
	server_auto_start?: boolean,
	/**  Stop the local server after this many idle minutes; 0 disables. */
	server_idle_unload_minutes?: number,
	/**  stdio language servers by name; None seeds the defaults. */
	lsp_servers?: LspServerConfig_Deserialize[] | null,
	/**  Which model plans vs executes; a distinct worker needs router mode. */
	harness_roles?: HarnessRoles_Deserialize,
	/**  External OpenAI-compatible providers (managed on the Mode tab). */
	providers?: Provider_Deserialize[],
	/**  External API mode: the `provider-id:model-id` the harness chats with. */
	external_target?: string | null,
	/**  Starred `provider-id:model-id` targets, pinned in the model picker. */
	provider_favorites?: string[],
	harness_role_params?: HarnessRoleParams_Deserialize,
	harness_projects?: HarnessProject[],
	/**  Project the chat view currently has open. */
	harness_active_project?: string | null,
	/**  Server process working dir; project fallback for the jail root. */
	server_working_dir?: string | null,
	/**  Model path -> preset name; applied on select, stored on start. */
	model_presets?: { [key in string]: string },
	/**  Last applied preset name; restored at startup when it still exists. */
	last_preset?: string | null,
	/**  Show the Quick Bench card on the Run page. */
	bench_visible?: boolean,
	/**  Delete older builds of the same backend when a new one installs. */
	auto_delete_old_runtimes?: boolean,
	/**  HuggingFace sources in preference order (browse filter). */
	preferred_owners?: string[],
	/**  Built-in server file tools for every run (subset of known names). */
	server_tools?: string[],
	/**  MCP servers disabled by name (mcp.json stays complete). */
	mcp_disabled?: string[],
	/**  Closing hides to the tray instead of quitting. */
	close_to_tray?: boolean,
	/**  Check for updates when Settings opens. */
	auto_check_updates?: boolean,
	/**  Notification sounds; all default on. */
	sound_agent?: boolean,
	sound_permissions?: boolean,
	sound_errors?: boolean,
};

export type AppConfig_Serialize = {
	version: number,
	/**  First-launch wizard done; `--force-wizard` clears it for this run. */
	wizard_completed: boolean,
	managed_runtimes: ManagedRuntime[],
	custom_runtimes: CustomRuntime[],
	active_runtime: ActiveRuntime,
	model_dirs: string[],
	download_dir: string | null,
	favorite_models: string[],
	selected_model: string | null,
	plugin_disabled: string[],
	/**  Turn budget for the orchestrator loop. */
	harness_max_turns: number,
	/**  Turn budget per subagent run. */
	harness_subagent_max_turns: number,
	/**  Verification-nudge strictness for the agent loop. */
	verify_mode: VerifyMode,
	/**  Custom system prompt override; None means the built-in default. */
	harness_system_prompt?: string | null,
	/**  Named system prompt presets (quick swap in Settings). */
	system_prompt_presets?: SystemPromptPreset[],
	/**  Agent (coding harness) or Roleplay (character cards). */
	chat_profile: ChatProfile,
	/**  Roleplay: active card, persona, greeting, sampling overrides. */
	roleplay: RoleplayConfig_Serialize,
	/**
	 *  Housekeeping model for compaction and distillation: a `provider:model`
	 *  target or a local role (`orchestrator`/`worker`). None = main model.
	 */
	utility_target?: string | null,
	/**  Language-server diagnostics after edits and the `lsp` query tool. */
	lsp_enabled: boolean,
	/**  Single-model or router server mode (Mode tab). */
	server_mode: ServerMode,
	/**  Agent tool names the harness must not offer; empty enables all. */
	agent_tools_disabled: string[],
	/**  Hide `AGENTS.md`/`.agent*` files from every agent tool when set. */
	agent_files_hidden: boolean,
	/**  Extra sensitive-file globs for agent tools (on top of the built-ins). */
	sensitive_patterns: string[],
	/**  Exceptions to the sensitive-file policy (globs). */
	sensitive_allow: string[],
	/**  Start the local server automatically when a chat run begins. */
	server_auto_start: boolean,
	/**  Stop the local server after this many idle minutes; 0 disables. */
	server_idle_unload_minutes: number,
	/**  stdio language servers by name; None seeds the defaults. */
	lsp_servers?: LspServerConfig_Serialize[] | null,
	/**  Which model plans vs executes; a distinct worker needs router mode. */
	harness_roles: HarnessRoles_Serialize,
	/**  External OpenAI-compatible providers (managed on the Mode tab). */
	providers: Provider_Serialize[],
	/**  External API mode: the `provider-id:model-id` the harness chats with. */
	external_target?: string | null,
	/**  Starred `provider-id:model-id` targets, pinned in the model picker. */
	provider_favorites: string[],
	harness_role_params: HarnessRoleParams_Serialize,
	harness_projects: HarnessProject[],
	/**  Project the chat view currently has open. */
	harness_active_project: string | null,
	/**  Server process working dir; project fallback for the jail root. */
	server_working_dir: string | null,
	/**  Model path -> preset name; applied on select, stored on start. */
	model_presets: { [key in string]: string },
	/**  Last applied preset name; restored at startup when it still exists. */
	last_preset?: string | null,
	/**  Show the Quick Bench card on the Run page. */
	bench_visible: boolean,
	/**  Delete older builds of the same backend when a new one installs. */
	auto_delete_old_runtimes: boolean,
	/**  HuggingFace sources in preference order (browse filter). */
	preferred_owners: string[],
	/**  Built-in server file tools for every run (subset of known names). */
	server_tools: string[],
	/**  MCP servers disabled by name (mcp.json stays complete). */
	mcp_disabled: string[],
	/**  Closing hides to the tray instead of quitting. */
	close_to_tray: boolean,
	/**  Check for updates when Settings opens. */
	auto_check_updates: boolean,
	/**  Notification sounds; all default on. */
	sound_agent: boolean,
	sound_permissions: boolean,
	sound_errors: boolean,
};

export type AssetDto = {
	name: string,
	backend_id: string,
	backend_label: string,
	size_mb: number | null,
	score: number,
};

/**  Auto-attached companion file; `auto` ones can be toggled off. */
export type AttachmentInfo = {
	kind: string,
	path: string,
	enabled: boolean,
	auto: boolean,
	/**  Router role that owns it ("orchestrator"/"worker"); None = single model. */
	role?: string | null,
};

export type AttachmentRead = AttachmentRead_Serialize | AttachmentRead_Deserialize;

export type AttachmentRead_Deserialize = {
	kind: string,
	name: string,
	data_base64?: string | null,
	text?: string | null,
};

export type AttachmentRead_Serialize = {
	kind: string,
	name: string,
	data_base64?: string | null,
	text?: string | null,
};

export type BackendDto = BackendDto_Serialize | BackendDto_Deserialize;

export type BackendDto_Deserialize = {
	id: string,
	label: string,
	available: boolean,
	version?: string | null,
};

export type BackendDto_Serialize = {
	id: string,
	label: string,
	available: boolean,
	version?: string | null,
};

/**  Wire result: floats are t/s (nullable when unparsed), time is unix secs. */
export type BenchResult = BenchResult_Serialize | BenchResult_Deserialize;

/**  Wire result: floats are t/s (nullable when unparsed), time is unix secs. */
export type BenchResult_Deserialize = {
	model_path: string,
	model_name: string,
	n_prompt: number,
	n_gen: number,
	n_gpu_layers: number,
	pp_tps?: number | null,
	tg_tps?: number | null,
	status: string,
	timestamp: number,
};

/**  Wire result: floats are t/s (nullable when unparsed), time is unix secs. */
export type BenchResult_Serialize = {
	model_path: string,
	model_name: string,
	n_prompt: number,
	n_gen: number,
	n_gpu_layers: number,
	pp_tps?: number | null,
	tg_tps?: number | null,
	status: string,
	timestamp: number,
};

export type BuiltinToolDto = {
	name: string,
	summary: string,
	approval: string,
	note: string,
	enabled: boolean,
};

export type CardSummary = {
	id: string,
	name: string,
	spec: string,
	tags: string[],
	greetings: number,
	has_avatar: boolean,
};

export type CharacterCard = {
	id: string,
	name: string,
	spec: string,
	description: string,
	personality: string,
	scenario: string,
	first_mes: string,
	alternate_greetings: string[],
	mes_example: string,
	system_prompt: string,
	post_history_instructions: string,
	creator_notes: string,
	tags: string[],
	lorebook: LorebookEntry[],
};

/**  Chat profile: the coding agent, the llama.cpp Web UI, or roleplay. */
export type ChatProfile = "agent" | "webui" | "roleplay";

/**  Live context gauge: slot usage first, GGUF length as fallback. */
export type ContextStats = ContextStats_Serialize | ContextStats_Deserialize;

/**  Live context gauge: slot usage first, GGUF length as fallback. */
export type ContextStats_Deserialize = {
	used?: number | null,
	total?: number | null,
};

/**  Live context gauge: slot usage first, GGUF length as fallback. */
export type ContextStats_Serialize = {
	used?: number | null,
	total?: number | null,
};

export type CustomRuntime = {
	label: string,
	binary_path: string,
};

export type CustomRuntimeDto = {
	label: string,
	binary_path: string,
};

/**  One estimate note; warnings highlight, info stays quiet. */
export type EstimateNote = {
	text: string,
	warn: boolean,
};

export type FoundBinaryDto = {
	binary_path: string,
	label: string,
};

export type GpuDto = {
	name: string,
	vram_mb: number,
};

/**  Model badges for the input row (orchestrator model wins). */
export type HarnessCapabilities = HarnessCapabilities_Serialize | HarnessCapabilities_Deserialize;

/**  Model badges for the input row (orchestrator model wins). */
export type HarnessCapabilities_Deserialize = {
	vision: boolean,
	reasoning: boolean,
	context_length?: number | null,
};

/**  Model badges for the input row (orchestrator model wins). */
export type HarnessCapabilities_Serialize = {
	vision: boolean,
	reasoning: boolean,
	context_length?: number | null,
};

/**  A chat project: a working directory the agent is sandboxed to. */
export type HarnessProject = {
	id: string,
	name: string,
	path: string,
	created?: number,
	/**  Extra read-only paths outside the project root. */
	extra_read?: string[],
};

export type HarnessRoleParams = HarnessRoleParams_Serialize | HarnessRoleParams_Deserialize;

export type HarnessRoleParams_Deserialize = {
	orchestrator?: RoleServerParams_Deserialize,
	worker?: RoleServerParams_Deserialize,
};

export type HarnessRoleParams_Serialize = {
	orchestrator: RoleServerParams_Serialize,
	worker: RoleServerParams_Serialize,
};

/**  Model roles; None uses the server's loaded model. */
export type HarnessRoles = HarnessRoles_Serialize | HarnessRoles_Deserialize;

/**  Model roles; None uses the server's loaded model. */
export type HarnessRoles_Deserialize = {
	orchestrator?: string | null,
	worker?: string | null,
};

/**  Model roles; None uses the server's loaded model. */
export type HarnessRoles_Serialize = {
	orchestrator?: string | null,
	worker?: string | null,
};

/**  Wire repo file; sizes ride f64 (exact to 9 PB in JSON). */
export type HfFileDto = HfFileDto_Serialize | HfFileDto_Deserialize;

/**  Wire repo file; sizes ride f64 (exact to 9 PB in JSON). */
export type HfFileDto_Deserialize = {
	path: string,
	size_bytes?: number | null,
};

/**  Wire repo file; sizes ride f64 (exact to 9 PB in JSON). */
export type HfFileDto_Serialize = {
	path: string,
	size_bytes?: number | null,
};

/**  Wire search hit (counts fit u32 with room to spare). */
export type HfModel = {
	repo_id: string,
	name: string,
	author: string,
	tags?: string[],
	downloads: number,
	likes: number,
};

/**
 *  Flat wire copy of a transcript message; multimodal content splits
 *  into text plus image URLs.
 */
export type HistoryMessage = HistoryMessage_Serialize | HistoryMessage_Deserialize;

/**
 *  Flat wire copy of a transcript message; multimodal content splits
 *  into text plus image URLs.
 */
export type HistoryMessage_Deserialize = {
	role: string,
	content?: string | null,
	images?: string[] | null,
	tool_calls?: HistoryToolCall[] | null,
	tool_call_id?: string | null,
};

/**
 *  Flat wire copy of a transcript message; multimodal content splits
 *  into text plus image URLs.
 */
export type HistoryMessage_Serialize = {
	role: string,
	content?: string | null,
	images?: string[] | null,
	tool_calls?: HistoryToolCall[] | null,
	tool_call_id?: string | null,
};

export type HistoryToolCall = {
	id: string,
	name: string,
	arguments: string,
};

export type HistoryView = HistoryView_Serialize | HistoryView_Deserialize;

export type HistoryView_Deserialize = {
	messages: HistoryMessage_Deserialize[],
	meta: MetaEntry_Deserialize[],
	todos?: TodoDto[],
};

export type HistoryView_Serialize = {
	messages: HistoryMessage_Serialize[],
	meta: MetaEntry_Serialize[],
	todos: TodoDto[],
};

export type KnownOwnerDto = {
	id: string,
	description: string,
};

/**  Wire-ready launch command for the Run page (same prep as `start_server`). */
export type LaunchPreview = {
	binary: string,
	args: string[],
	notes: string[],
	attachments: AttachmentInfo[],
	/**
	 *  Router resource-management note (VRAM/RAM plan); shown with the memory
	 *  estimate, not the launch command.
	 */
	residency?: string | null,
};

export type LorebookEntry = {
	comment: string,
	keys: string[],
	content: string,
	constant: boolean,
	enabled: boolean,
	order: number,
};

/**  A user-defined language server, spawned over stdio. */
export type LspServerConfig = LspServerConfig_Serialize | LspServerConfig_Deserialize;

/**  A user-defined language server, spawned over stdio. */
export type LspServerConfig_Deserialize = {
	name: string,
	/**  Command line; the first token is the program, the rest are argv. */
	command: string,
	/**  File extensions, with or without a leading dot. */
	extensions: string[],
	/**  LSP languageId sent on didOpen; None uses the extension itself. */
	language?: string | null,
	/**  Workspace-root marker files, nearest ancestor wins; empty = project root. */
	roots?: string[] | null,
};

/**  A user-defined language server, spawned over stdio. */
export type LspServerConfig_Serialize = {
	name: string,
	/**  Command line; the first token is the program, the rest are argv. */
	command: string,
	/**  File extensions, with or without a leading dot. */
	extensions: string[],
	/**  LSP languageId sent on didOpen; None uses the extension itself. */
	language?: string | null,
	/**  Workspace-root marker files, nearest ancestor wins; empty = project root. */
	roots?: string[] | null,
};

export type ManagedRuntime = {
	build: number,
	tag_name: string,
	backend_id: string,
	backend_label: string,
	asset_name: string,
	/**  Subdirectory name under the runtimes base dir */
	dir_name: string,
	/**  Unix seconds (u32: exact in JSON, good until 2106). */
	installed_at: number,
};

export type McpInfo = {
	path: string,
	servers: McpServerEntry[],
};

export type McpServerEntry = {
	name: string,
	command: string,
	args?: string[],
	env?: { [key in string]: string },
	cwd?: string | null,
	timeout_ms?: number | null,
	/**  App-side toggle; persisted separately so mcp.json stays portable. */
	enabled?: boolean,
};

/**  Per-server MCP state for the Tools → Live view. */
export type McpServerStatus = McpServerStatus_Serialize | McpServerStatus_Deserialize;

/**  Per-server MCP state for the Tools → Live view. */
export type McpServerStatus_Deserialize = {
	name: string,
	running: boolean,
	tools: string[],
	error?: string | null,
};

/**  Per-server MCP state for the Tools → Live view. */
export type McpServerStatus_Serialize = {
	name: string,
	running: boolean,
	tools: string[],
	error?: string | null,
};

/**  Estimated memory breakdown for a model + settings on the current machine. */
export type MemoryEstimate = {
	model_mb: number,
	kv_cache_mb: number,
	overhead_mb: number,
	total_mb: number,
	vram_total_mb: number,
	ram_available_mb: number,
	vram_used_mb: number,
	ram_used_mb: number,
	vram_model_mb: number,
	vram_kv_mb: number,
	vram_overhead_mb: number,
	ram_model_mb: number,
	ram_kv_mb: number,
	ram_overhead_mb: number,
	fits: boolean,
	/**  Fits the raw total but leaves nothing for CUDA/OS headroom. */
	tight: boolean,
	notes: EstimateNote[],
};

/**  One editable memory file: where it lives and what it says. */
export type MemoryFileDto = MemoryFileDto_Serialize | MemoryFileDto_Deserialize;

/**  One editable memory file: where it lives and what it says. */
export type MemoryFileDto_Deserialize = {
	scope: string,
	path: string,
	exists: boolean,
	text: string,
	/**  Pre-`/distill` copy, when one exists. */
	backup?: string | null,
};

/**  One editable memory file: where it lives and what it says. */
export type MemoryFileDto_Serialize = {
	scope: string,
	path: string,
	exists: boolean,
	text: string,
	/**  Pre-`/distill` copy, when one exists. */
	backup?: string | null,
};

/**
 *  Footer stats for one assistant message. Integers are 32-bit: exact in
 *  JSON and far beyond physical counts (u32 tokens, unix seconds to 2106).
 */
export type MessageMeta = MessageMeta_Serialize | MessageMeta_Deserialize;

/**
 *  Footer stats for one assistant message. Integers are 32-bit: exact in
 *  JSON and far beyond physical counts (u32 tokens, unix seconds to 2106).
 */
export type MessageMeta_Deserialize = {
	model?: string | null,
	tokens_per_sec?: number | null,
	gen_tokens?: number | null,
	prompt_tokens?: number | null,
	elapsed_ms?: number | null,
	/**  Accumulated reasoning; shown in a collapsible block, never resent. */
	reasoning?: string | null,
	/**  Files the agent changed during the run that produced this message. */
	changes?: RunChanges | null,
};

/**
 *  Footer stats for one assistant message. Integers are 32-bit: exact in
 *  JSON and far beyond physical counts (u32 tokens, unix seconds to 2106).
 */
export type MessageMeta_Serialize = {
	model?: string | null,
	tokens_per_sec?: number | null,
	gen_tokens?: number | null,
	prompt_tokens?: number | null,
	elapsed_ms?: number | null,
	/**  Accumulated reasoning; shown in a collapsible block, never resent. */
	reasoning?: string | null,
	/**  Files the agent changed during the run that produced this message. */
	changes?: RunChanges | null,
};

export type MetaEntry = MetaEntry_Serialize | MetaEntry_Deserialize;

export type MetaEntry_Deserialize = {
	index: number,
	meta: MessageMeta_Deserialize,
};

export type MetaEntry_Serialize = {
	index: number,
	meta: MessageMeta_Serialize,
};

export type ModelDirs = {
	dirs: string[],
	download_dir: string,
};

/**  Wire copy of a model (byte sizes as f64: exact to 9 PB in JSON). */
export type ModelDto = ModelDto_Serialize | ModelDto_Deserialize;

/**  Wire copy of a model (byte sizes as f64: exact to 9 PB in JSON). */
export type ModelDto_Deserialize = {
	id: string,
	name: string,
	filename: string,
	path: string,
	size_bytes: number | null,
	quant?: string | null,
	params_b?: string | null,
	context_length?: number | null,
	architecture?: string | null,
	is_vision: boolean,
	is_reasoning: boolean,
	mmproj_path?: string | null,
	hf_repo?: string | null,
};

/**  Wire copy of a model (byte sizes as f64: exact to 9 PB in JSON). */
export type ModelDto_Serialize = {
	id: string,
	name: string,
	filename: string,
	path: string,
	size_bytes: number | null,
	quant?: string | null,
	params_b?: string | null,
	context_length?: number | null,
	architecture?: string | null,
	is_vision: boolean,
	is_reasoning: boolean,
	mmproj_path?: string | null,
	hf_repo?: string | null,
};

/**  OS + desktop idiom for corner/shape theming. */
export type PlatformStyle = {
	os: string,
	/**  "sharp" (Windows 10, KDE) or "round" (macOS, Windows 11, GNOME). */
	corners: string,
	desktop: string,
};

export type PluginDto = {
	name: string,
	description: string,
	scope: string,
	dir: string,
	enabled: boolean,
	approval: boolean,
};

export type PluginErrorDto = {
	dir: string,
	error: string,
};

/**  One entry in the Chat sidebar's project tree. */
export type ProjectFileEntry = ProjectFileEntry_Serialize | ProjectFileEntry_Deserialize;

/**  One entry in the Chat sidebar's project tree. */
export type ProjectFileEntry_Deserialize = {
	/**  Forward-slash path relative to the project root. */
	path: string,
	name: string,
	dir: boolean,
	/**  Changed on disk per `git status` (includes untracked files). */
	changed: boolean,
	/**  Written or edited by the agent in the current session. */
	touched: boolean,
	size?: number | null,
};

/**  One entry in the Chat sidebar's project tree. */
export type ProjectFileEntry_Serialize = {
	/**  Forward-slash path relative to the project root. */
	path: string,
	name: string,
	dir: boolean,
	/**  Changed on disk per `git status` (includes untracked files). */
	changed: boolean,
	/**  Written or edited by the agent in the current session. */
	touched: boolean,
	size?: number | null,
};

export type ProjectFiles = ProjectFiles_Serialize | ProjectFiles_Deserialize;

export type ProjectFiles_Deserialize = {
	root: string,
	git: boolean,
	/**  The scan hit its entry cap; the tree is incomplete. */
	truncated: boolean,
	entries: ProjectFileEntry_Deserialize[],
};

export type ProjectFiles_Serialize = {
	root: string,
	git: boolean,
	/**  The scan hit its entry cap; the tree is incomplete. */
	truncated: boolean,
	entries: ProjectFileEntry_Serialize[],
};

/**
 *  An external OpenAI-compatible provider (cloud API or another local
 *  server). External API mode targets it as `provider-id:model-id`.
 */
export type Provider = Provider_Serialize | Provider_Deserialize;

/**
 *  An external OpenAI-compatible provider (cloud API or another local
 *  server). External API mode targets it as `provider-id:model-id`.
 */
export type Provider_Deserialize = {
	id: string,
	base_url: string,
	api_key?: string | null,
	models?: string[],
	/**  Declared context window for its models; None = unknown. */
	context_length?: number | null,
};

/**
 *  An external OpenAI-compatible provider (cloud API or another local
 *  server). External API mode targets it as `provider-id:model-id`.
 */
export type Provider_Serialize = {
	id: string,
	base_url: string,
	api_key?: string | null,
	models: string[],
	/**  Declared context window for its models; None = unknown. */
	context_length?: number | null,
};

/**
 *  Reasoning effort levels from the active model's chat template.
 *  Others 500 — hidden for non-reasoning models.
 */
export type ReasoningOptions = {
	supported: boolean,
	levels: string[],
};

/**  Wire entry: sizes in MB, installed matched by filename. */
export type RecommendedDto = RecommendedDto_Serialize | RecommendedDto_Deserialize;

/**  Wire entry: sizes in MB, installed matched by filename. */
export type RecommendedDto_Deserialize = {
	repo_id: string,
	filename: string,
	name: string,
	description: string,
	params_b: number,
	quant: string,
	estimated_size_mb: number,
	context?: number | null,
	installed: boolean,
};

/**  Wire entry: sizes in MB, installed matched by filename. */
export type RecommendedDto_Serialize = {
	repo_id: string,
	filename: string,
	name: string,
	description: string,
	params_b: number,
	quant: string,
	estimated_size_mb: number,
	context?: number | null,
	installed: boolean,
};

export type ReleaseDto = {
	tag_name: string,
	build: number,
	assets: AssetDto[],
};

/**  Per-role server overrides written into the router preset; None inherits. */
export type RoleServerParams = RoleServerParams_Serialize | RoleServerParams_Deserialize;

/**  Per-role server overrides written into the router preset; None inherits. */
export type RoleServerParams_Deserialize = {
	ctx_size?: number | null,
	n_gpu_layers?: number | null,
	/**  Detached companion files: sibling stays on disk but is not loaded. */
	no_chat_template?: boolean,
	no_mmproj?: boolean,
	no_draft?: boolean,
};

/**  Per-role server overrides written into the router preset; None inherits. */
export type RoleServerParams_Serialize = {
	ctx_size?: number | null,
	n_gpu_layers?: number | null,
	/**  Detached companion files: sibling stays on disk but is not loaded. */
	no_chat_template?: boolean,
	no_mmproj?: boolean,
	no_draft?: boolean,
};

/**
 *  Roleplay profile state: active card, user persona, greeting index, and
 *  per-request sampling overrides (None = server defaults).
 */
export type RoleplayConfig = RoleplayConfig_Serialize | RoleplayConfig_Deserialize;

/**
 *  Roleplay profile state: active card, user persona, greeting index, and
 *  per-request sampling overrides (None = server defaults).
 */
export type RoleplayConfig_Deserialize = {
	card_id?: string | null,
	greeting?: number,
	user_name?: string,
	user_description?: string,
	temperature?: number | null,
	top_p?: number | null,
	repeat_penalty?: number | null,
	/**  Imported avatar image for the user's chat bubbles. */
	user_avatar?: string | null,
};

/**
 *  Roleplay profile state: active card, user persona, greeting index, and
 *  per-request sampling overrides (None = server defaults).
 */
export type RoleplayConfig_Serialize = {
	card_id?: string | null,
	greeting: number,
	user_name: string,
	user_description: string,
	temperature?: number | null,
	top_p?: number | null,
	repeat_penalty?: number | null,
	/**  Imported avatar image for the user's chat bubbles. */
	user_avatar?: string | null,
};

export type RouterModelStatus = {
	id: string,
	status: string,
};

/**  One file the agent changed in a run, with git line counts. */
export type RunChange = {
	path: string,
	status: string,
	added: number,
	removed: number,
};

export type RunChanges = {
	files: RunChange[],
	added: number,
	removed: number,
};

/**  Agent run result: text plus the metadata shown under each response. */
export type RunResult = RunResult_Serialize | RunResult_Deserialize;

/**  Agent run result: text plus the metadata shown under each response. */
export type RunResult_Deserialize = {
	text: string,
	model?: string | null,
	tokens_per_sec?: number | null,
	gen_tokens: number,
	prompt_tokens?: number | null,
	elapsed_ms: number,
	reasoning?: string | null,
	changes?: RunChanges | null,
};

/**  Agent run result: text plus the metadata shown under each response. */
export type RunResult_Serialize = {
	text: string,
	model?: string | null,
	tokens_per_sec?: number | null,
	gen_tokens: number,
	prompt_tokens?: number | null,
	elapsed_ms: number,
	reasoning?: string | null,
	changes?: RunChanges | null,
};

export type RuntimeInfo = RuntimeInfo_Serialize | RuntimeInfo_Deserialize;

export type RuntimeInfo_Deserialize = {
	managed: ManagedRuntime[],
	custom: CustomRuntimeDto[],
	active: ActiveRuntime,
	server_binary?: string | null,
	/**  Runtimes root; managed builds live in `<base_dir>/<dir_name>`. */
	base_dir: string,
};

export type RuntimeInfo_Serialize = {
	managed: ManagedRuntime[],
	custom: CustomRuntimeDto[],
	active: ActiveRuntime,
	server_binary?: string | null,
	/**  Runtimes root; managed builds live in `<base_dir>/<dir_name>`. */
	base_dir: string,
};

/**  A user-picked file: images ride as data URLs, text inlines. */
export type SendAttachment = SendAttachment_Serialize | SendAttachment_Deserialize;

/**  A user-picked file: images ride as data URLs, text inlines. */
export type SendAttachment_Deserialize = {
	name: string,
	kind: string,
	path?: string | null,
	data_base64?: string | null,
	text?: string | null,
};

/**  A user-picked file: images ride as data URLs, text inlines. */
export type SendAttachment_Serialize = {
	name: string,
	kind: string,
	path?: string | null,
	data_base64?: string | null,
	text?: string | null,
};

export type ServerConfig = {
	/**  Empty means router mode (models come from the preset file). */
	model_path: string,
	mmproj_path?: string | null,
	host: string,
	port: number,
	/**  0 = auto (omit --ctx-size). */
	n_ctx: number,
	/**  -1 = all layers on GPU, 0 = CPU only. */
	n_gpu_layers: number,
	n_threads?: number | null,
	flash_attn?: string,
	cache_type_k?: string,
	cache_type_v?: string,
	temperature: number | null,
	top_k: number,
	min_p: number | null,
	top_p: number | null,
	/**  -1 = unlimited. */
	n_predict: number,
	/**  True = no sampling flags at all (server/harness defaults apply). */
	disable_sampling?: boolean,
	/**  0 = omit (server default). */
	n_batch: number,
	/**  0 = omit (server default). */
	n_ubatch: number,
	cont_batching: boolean,
	seed?: number | null,
	rope_freq_scale?: number | null,
	rope_freq_base?: number | null,
	parallel: number,
	/**  Child process working directory. */
	working_dir?: string | null,
	/**
	 *  Extra CLI flags: key = flag without `--`, value = argument.
	 *  `__raw__` holds free-form text appended verbatim.
	 */
	extra_params?: { [key in string]: string },
};

/**  Wire server info; counts fit u32 with room to spare. */
export type ServerInfo = ServerInfo_Serialize | ServerInfo_Deserialize;

/**  Wire server info; counts fit u32 with room to spare. */
export type ServerInfo_Deserialize = {
	base_url: string,
	model_id: string,
	model_alias: string,
	model_path: string,
	n_ctx: number,
	n_predict: number,
	total_slots: number,
	slots_idle: number,
	api_key?: string | null,
	models?: RouterModelStatus[],
	router_mode: boolean,
};

/**  Wire server info; counts fit u32 with room to spare. */
export type ServerInfo_Serialize = {
	base_url: string,
	model_id: string,
	model_alias: string,
	model_path: string,
	n_ctx: number,
	n_predict: number,
	total_slots: number,
	slots_idle: number,
	api_key?: string | null,
	models: RouterModelStatus[],
	router_mode: boolean,
};

/**
 *  How the harness gets its model: one local model, a local router, or an
 *  external OpenAI-compatible API (no local server).
 */
export type ServerMode = "single" | "router" | "external";

export type ServerStatus = { type: "stopped" } | { type: "starting" } | { type: "running"; port: number; pid: number; 
/**
 *  True once the process logs "listening on …" — before that the
 *  model is still loading.
 */
ready: boolean } | { type: "error"; message: string };

export type ServerToolInfo = {
	name: string,
	display_name: string,
	type: string,
	description: string,
};

export type SessionSummary = SessionSummary_Serialize | SessionSummary_Deserialize;

export type SessionSummary_Deserialize = {
	id: string,
	title: string,
	project?: string | null,
	updated: number,
	message_count: number,
};

export type SessionSummary_Serialize = {
	id: string,
	title: string,
	project?: string | null,
	updated: number,
	message_count: number,
};

export type SkillDto = {
	name: string,
	description: string,
	scope: string,
	dir: string,
};

/**  Suggested launch knobs; the estimator always picks an explicit context. */
export type SuggestedConfig = {
	n_gpu_layers: number,
	n_ctx: number,
	can_fit_fully_in_vram: boolean,
	total_usable_mb: number,
	notes: string[],
	n_threads: number | null,
	n_batch: number | null,
	n_ubatch: number | null,
};

/**  Wire system info; RAM/VRAM are integers (exact in JSON under 2^53). */
export type SystemInfoDto = SystemInfoDto_Serialize | SystemInfoDto_Deserialize;

/**  Wire system info; RAM/VRAM are integers (exact in JSON under 2^53). */
export type SystemInfoDto_Deserialize = {
	cpu_name: string,
	cpu_cores: number,
	cpu_threads: number,
	total_ram_mb: number,
	available_ram_mb: number,
	gpus: GpuDto[],
	os: string,
	arch: string,
	backends: BackendDto_Deserialize[],
	recommended_backend: string,
};

/**  Wire system info; RAM/VRAM are integers (exact in JSON under 2^53). */
export type SystemInfoDto_Serialize = {
	cpu_name: string,
	cpu_cores: number,
	cpu_threads: number,
	total_ram_mb: number,
	available_ram_mb: number,
	gpus: GpuDto[],
	os: string,
	arch: string,
	backends: BackendDto_Serialize[],
	recommended_backend: string,
};

/**  A named system prompt the user can swap in from Settings. */
export type SystemPromptPreset = {
	name: string,
	prompt: string,
};

/**  One checkpoint in the orchestrator's task list. */
export type TodoDto = {
	text: string,
	done: boolean,
};

export type ToolsList = {
	builtin: BuiltinToolDto[],
	plugins: PluginDto[],
	plugin_errors: PluginErrorDto[],
	plugins_dir: string,
};

/**
 *  Strictness: Off silences the detector, Normal fires on unchecked turns,
 *  Thorough also fires on turns that read.
 */
export type VerifyMode = "off" | "normal" | "thorough";

export type WorktreeDto = WorktreeDto_Serialize | WorktreeDto_Deserialize;

export type WorktreeDto_Deserialize = {
	path: string,
	branch?: string | null,
	head?: string | null,
	bare: boolean,
	main: boolean,
};

export type WorktreeDto_Serialize = {
	path: string,
	branch?: string | null,
	head?: string | null,
	bare: boolean,
	main: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

